# Generated by Django 5.1.4 on 2024-12-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
