# Generated by Django 5.1.4 on 2024-12-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
