# Generated by Django 5.1.4 on 2024-12-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddocument',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
