# Generated by Django 5.1.4 on 2024-12-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_manager_type'),
        ('user', '0003_alter_user_table'),
    ]

    operations = [
    ]
